/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAudienciasRouteImport } from './routes/_authenticated/audiencias'
import { Route as AuthenticatedBiRouteImport } from './routes/_authenticated/bi'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedModelosRouteImport } from './routes/_authenticated/modelos'
import { Route as AuthenticatedPericiasRouteImport } from './routes/_authenticated/pericias'
import { Route as AuthenticatedPrazosRouteImport } from './routes/_authenticated/prazos'
import { Route as AuthenticatedProcessosRouteImport } from './routes/_authenticated/processos'
import { Route as AuthenticatedResumoRouteImport } from './routes/_authenticated/resumo'
import { Route as AuthenticatedFinanceiroDreRouteImport } from './routes/_authenticated/financeiro.dre'
import { Route as AuthenticatedFinanceiroLancamentosRouteImport } from './routes/_authenticated/financeiro.lancamentos'
import { Route as AuthenticatedFinanceiroPlanoContasRouteImport } from './routes/_authenticated/financeiro.plano-contas'
import { Route as AuthenticatedProcessosIdRouteImport } from './routes/_authenticated/processos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAudienciasRoute = AuthenticatedAudienciasRouteImport.update({
  id: '/audiencias',
  path: '/audiencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBiRoute = AuthenticatedBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelosRoute = AuthenticatedModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPericiasRoute = AuthenticatedPericiasRouteImport.update({
  id: '/pericias',
  path: '/pericias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrazosRoute = AuthenticatedPrazosRouteImport.update({
  id: '/prazos',
  path: '/prazos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessosRoute = AuthenticatedProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumoRoute = AuthenticatedResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroDreRoute =
  AuthenticatedFinanceiroDreRouteImport.update({
    id: '/financeiro/dre',
    path: '/financeiro/dre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroLancamentosRoute =
  AuthenticatedFinanceiroLancamentosRouteImport.update({
    id: '/financeiro/lancamentos',
    path: '/financeiro/lancamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroPlanoContasRoute =
  AuthenticatedFinanceiroPlanoContasRouteImport.update({
    id: '/financeiro/plano-contas',
    path: '/financeiro/plano-contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessosIdRoute =
  AuthenticatedProcessosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedProcessosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audiencias': typeof AuthenticatedAudienciasRoute
  '/bi': typeof AuthenticatedBiRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/pericias': typeof AuthenticatedPericiasRoute
  '/prazos': typeof AuthenticatedPrazosRoute
  '/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/resumo': typeof AuthenticatedResumoRoute
  '/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/financeiro/lancamentos': typeof AuthenticatedFinanceiroLancamentosRoute
  '/financeiro/plano-contas': typeof AuthenticatedFinanceiroPlanoContasRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audiencias': typeof AuthenticatedAudienciasRoute
  '/bi': typeof AuthenticatedBiRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/pericias': typeof AuthenticatedPericiasRoute
  '/prazos': typeof AuthenticatedPrazosRoute
  '/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/resumo': typeof AuthenticatedResumoRoute
  '/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/financeiro/lancamentos': typeof AuthenticatedFinanceiroLancamentosRoute
  '/financeiro/plano-contas': typeof AuthenticatedFinanceiroPlanoContasRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audiencias': typeof AuthenticatedAudienciasRoute
  '/_authenticated/bi': typeof AuthenticatedBiRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/modelos': typeof AuthenticatedModelosRoute
  '/_authenticated/pericias': typeof AuthenticatedPericiasRoute
  '/_authenticated/prazos': typeof AuthenticatedPrazosRoute
  '/_authenticated/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/_authenticated/resumo': typeof AuthenticatedResumoRoute
  '/_authenticated/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/_authenticated/financeiro/lancamentos': typeof AuthenticatedFinanceiroLancamentosRoute
  '/_authenticated/financeiro/plano-contas': typeof AuthenticatedFinanceiroPlanoContasRoute
  '/_authenticated/processos/$id': typeof AuthenticatedProcessosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audiencias'
    | '/bi'
    | '/cadastros'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/integracoes'
    | '/modelos'
    | '/pericias'
    | '/prazos'
    | '/processos'
    | '/resumo'
    | '/financeiro/dre'
    | '/financeiro/lancamentos'
    | '/financeiro/plano-contas'
    | '/processos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audiencias'
    | '/bi'
    | '/cadastros'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/integracoes'
    | '/modelos'
    | '/pericias'
    | '/prazos'
    | '/processos'
    | '/resumo'
    | '/financeiro/dre'
    | '/financeiro/lancamentos'
    | '/financeiro/plano-contas'
    | '/processos/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audiencias'
    | '/_authenticated/bi'
    | '/_authenticated/cadastros'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/integracoes'
    | '/_authenticated/modelos'
    | '/_authenticated/pericias'
    | '/_authenticated/prazos'
    | '/_authenticated/processos'
    | '/_authenticated/resumo'
    | '/_authenticated/financeiro/dre'
    | '/_authenticated/financeiro/lancamentos'
    | '/_authenticated/financeiro/plano-contas'
    | '/_authenticated/processos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audiencias': {
      id: '/_authenticated/audiencias'
      path: '/audiencias'
      fullPath: '/audiencias'
      preLoaderRoute: typeof AuthenticatedAudienciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bi': {
      id: '/_authenticated/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AuthenticatedBiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modelos': {
      id: '/_authenticated/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof AuthenticatedModelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pericias': {
      id: '/_authenticated/pericias'
      path: '/pericias'
      fullPath: '/pericias'
      preLoaderRoute: typeof AuthenticatedPericiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prazos': {
      id: '/_authenticated/prazos'
      path: '/prazos'
      fullPath: '/prazos'
      preLoaderRoute: typeof AuthenticatedPrazosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos': {
      id: '/_authenticated/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof AuthenticatedProcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumo': {
      id: '/_authenticated/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof AuthenticatedResumoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/dre': {
      id: '/_authenticated/financeiro/dre'
      path: '/financeiro/dre'
      fullPath: '/financeiro/dre'
      preLoaderRoute: typeof AuthenticatedFinanceiroDreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/lancamentos': {
      id: '/_authenticated/financeiro/lancamentos'
      path: '/financeiro/lancamentos'
      fullPath: '/financeiro/lancamentos'
      preLoaderRoute: typeof AuthenticatedFinanceiroLancamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/plano-contas': {
      id: '/_authenticated/financeiro/plano-contas'
      path: '/financeiro/plano-contas'
      fullPath: '/financeiro/plano-contas'
      preLoaderRoute: typeof AuthenticatedFinanceiroPlanoContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos/$id': {
      id: '/_authenticated/processos/$id'
      path: '/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof AuthenticatedProcessosIdRouteImport
      parentRoute: typeof AuthenticatedProcessosRoute
    }
  }
}

interface AuthenticatedProcessosRouteChildren {
  AuthenticatedProcessosIdRoute: typeof AuthenticatedProcessosIdRoute
}

const AuthenticatedProcessosRouteChildren: AuthenticatedProcessosRouteChildren =
  {
    AuthenticatedProcessosIdRoute: AuthenticatedProcessosIdRoute,
  }

const AuthenticatedProcessosRouteWithChildren =
  AuthenticatedProcessosRoute._addFileChildren(
    AuthenticatedProcessosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAudienciasRoute: typeof AuthenticatedAudienciasRoute
  AuthenticatedBiRoute: typeof AuthenticatedBiRoute
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedModelosRoute: typeof AuthenticatedModelosRoute
  AuthenticatedPericiasRoute: typeof AuthenticatedPericiasRoute
  AuthenticatedPrazosRoute: typeof AuthenticatedPrazosRoute
  AuthenticatedProcessosRoute: typeof AuthenticatedProcessosRouteWithChildren
  AuthenticatedResumoRoute: typeof AuthenticatedResumoRoute
  AuthenticatedFinanceiroDreRoute: typeof AuthenticatedFinanceiroDreRoute
  AuthenticatedFinanceiroLancamentosRoute: typeof AuthenticatedFinanceiroLancamentosRoute
  AuthenticatedFinanceiroPlanoContasRoute: typeof AuthenticatedFinanceiroPlanoContasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAudienciasRoute: AuthenticatedAudienciasRoute,
  AuthenticatedBiRoute: AuthenticatedBiRoute,
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedModelosRoute: AuthenticatedModelosRoute,
  AuthenticatedPericiasRoute: AuthenticatedPericiasRoute,
  AuthenticatedPrazosRoute: AuthenticatedPrazosRoute,
  AuthenticatedProcessosRoute: AuthenticatedProcessosRouteWithChildren,
  AuthenticatedResumoRoute: AuthenticatedResumoRoute,
  AuthenticatedFinanceiroDreRoute: AuthenticatedFinanceiroDreRoute,
  AuthenticatedFinanceiroLancamentosRoute:
    AuthenticatedFinanceiroLancamentosRoute,
  AuthenticatedFinanceiroPlanoContasRoute:
    AuthenticatedFinanceiroPlanoContasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
